bbox:
    DATA_PATH: "data/RGB"
    TRAIN_PATH: "data/train_bbox"
    VALID_PATH: "data/valid_bbox"
    TRAIN_DATA: "data/train_bbox/train.dat"
    TRAIN_TARGET_DATA: "data/train_bbox/train_target.dat"
    VALID_DATA: "data/valid_bbox/valid.dat"
    VALID_TARGET_DATA: "data/valid_bbox/valid_target.dat"
    WEIGHTS_PATH: "results/bbox_weights.h5"
    SIZE: !!python/tuple [4000, 3000]
    TARGET_SIZE: !!python/tuple [224, 224]
    VALID_PROP: 0.15

    LR: 0.01
    DECAY: 0
    BATCH_SIZE: 64
    EPOCHS: 30
ndvi:
    DATA_PATH: "data/NDVI_Predictor"
    TRAIN_PATH: "data/train_ndvi"
    VALID_PATH: "data/valid_ndvi"
    TRAIN_DATA: "data/train_ndvi/train.dat"
    TRAIN_TARGET_DATA: "data/train_ndvi/train_target.dat"
    VALID_DATA: "data/valid_ndvi/valid.dat"
    VALID_TARGET_DATA: "data/valid_ndvi/valid_target.dat"
    WEIGHTS_PATH: "results/ndvi_weights.h5"
    SIZE: !!python/tuple [4000, 3000]
    TARGET_SIZE: !!python/tuple [224, 224]
    VALID_EXT: !!python/tuple [".jpg", ".JPG"]
    VALID_PROP: 0.15

    LR: 0.01
    DECAY: 0
    BATCH_SIZE: 64
    EPOCHS: 100
    WIDTH_SHIFT_RANGE: 0.05
    HEIGHT_SHIFT_RANGE: 0.05
    ZOOM_RANGE: 0.05
